import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { AuditResponse, AuditRequest } from '../types';
import { ScoreChart } from './ScoreChart';
import { TechStackChart } from './TechStackChart';
import { generateReadme, generateUnitTests } from '../services/geminiService';

interface AuditResultProps {
  response: AuditResponse | null;
  repoData: AuditRequest | null;
}

export const AuditResult: React.FC<AuditResultProps> = ({ response, repoData }) => {
  const [actionLoading, setActionLoading] = useState<string | null>(null);
  const [generatedContent, setGeneratedContent] = useState<{title: string, content: string} | null>(null);

  if (!response) return null;

  const handleAction = async (action: 'readme' | 'tests') => {
    if (!repoData) return;
    
    setActionLoading(action);
    setGeneratedContent(null);
    
    try {
        let content = '';
        let title = '';
        
        if (action === 'readme') {
            title = 'Generated README.md';
            content = await generateReadme(repoData);
        } else {
            title = 'Generated Unit Tests';
            content = await generateUnitTests(repoData);
        }
        
        setGeneratedContent({ title, content });
        
        // Scroll to bottom
        setTimeout(() => {
            document.getElementById('ai-actions-result')?.scrollIntoView({ behavior: 'smooth' });
        }, 100);

    } catch (e) {
        console.error(e);
    } finally {
        setActionLoading(null);
    }
  };

  return (
    <div className="space-y-6">
        <div className="bg-slate-800 rounded-xl border border-slate-700 overflow-hidden shadow-2xl animate-fade-in">
        <div className="p-6 border-b border-slate-700 bg-slate-900/50 flex flex-col md:flex-row items-start justify-between gap-6">
            <div className="flex-1">
                <h2 className="text-2xl font-bold text-white mb-2">Audit Report</h2>
                <p className="text-slate-400 text-sm mb-4">Analysis generated by Senior Architect AI.</p>
                {/* Tech Stack Chart embedded here for desktop */}
                {repoData && (
                    <div className="max-w-md">
                        <TechStackChart data={repoData.languageDistribution} />
                    </div>
                )}
            </div>
            <div className="w-full md:w-64 shrink-0 bg-slate-900/50 rounded-xl p-4 border border-slate-700/50">
                <ScoreChart score={response.score} />
            </div>
        </div>
        
        <div className="p-8 prose prose-invert prose-slate max-w-none">
            <ReactMarkdown
            components={{
                h1: ({node, ...props}) => <h1 className="text-3xl font-extrabold text-white border-b border-slate-700 pb-4 mb-6" {...props} />,
                h2: ({node, ...props}) => <h2 className="text-xl font-bold text-blue-400 mt-8 mb-4 flex items-center" {...props} />,
                ul: ({node, ...props}) => <ul className="space-y-2 my-4" {...props} />,
                li: ({node, ...props}) => <li className="text-slate-300 ml-4" {...props} />,
                p: ({node, ...props}) => <p className="text-slate-300 leading-relaxed mb-4" {...props} />,
                strong: ({node, ...props}) => <strong className="font-bold text-white" {...props} />,
                blockquote: ({node, ...props}) => <blockquote className="border-l-4 border-blue-500 pl-4 italic text-slate-400 my-4" {...props} />,
            }}
            >
            {response.markdown.replace(/# 🛡️ GitHub Repository Audit\n\n## 📊 GitGrade Score: \[\d+-\d+\]\/100\n\*\(Rate strictly.*\)\*/g, '')} 
            </ReactMarkdown>
        </div>
        </div>

        {/* AI Actions Section */}
        <div className="bg-slate-800 rounded-xl border border-slate-700 p-6 shadow-xl">
            <h3 className="text-lg font-bold text-white mb-4 flex items-center gap-2">
                <span className="text-purple-400">✨</span> AI Assistant Actions
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <button 
                    onClick={() => handleAction('readme')}
                    disabled={!!actionLoading}
                    className="flex items-center justify-center gap-3 p-4 rounded-lg border border-slate-600 bg-slate-700/50 hover:bg-slate-700 hover:border-blue-500 transition-all group disabled:opacity-50"
                >
                    <div className="bg-blue-500/20 p-2 rounded-lg text-blue-400 group-hover:bg-blue-500 group-hover:text-white transition-colors">
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path></svg>
                    </div>
                    <div className="text-left">
                        <div className="font-bold text-white">Generate Better README</div>
                        <div className="text-xs text-slate-400">Professional docs based on code analysis</div>
                    </div>
                    {actionLoading === 'readme' && <svg className="animate-spin h-5 w-5 text-blue-400 ml-auto" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>}
                </button>

                <button 
                    onClick={() => handleAction('tests')}
                    disabled={!!actionLoading}
                    className="flex items-center justify-center gap-3 p-4 rounded-lg border border-slate-600 bg-slate-700/50 hover:bg-slate-700 hover:border-green-500 transition-all group disabled:opacity-50"
                >
                    <div className="bg-green-500/20 p-2 rounded-lg text-green-400 group-hover:bg-green-500 group-hover:text-white transition-colors">
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4"></path></svg>
                    </div>
                    <div className="text-left">
                        <div className="font-bold text-white">Generate Unit Tests</div>
                        <div className="text-xs text-slate-400">Create basic test suite boilerplate</div>
                    </div>
                    {actionLoading === 'tests' && <svg className="animate-spin h-5 w-5 text-green-400 ml-auto" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>}
                </button>
            </div>

            {generatedContent && (
                <div id="ai-actions-result" className="mt-6 border-t border-slate-700 pt-6 animate-fade-in">
                    <h4 className="text-white font-bold mb-2 flex items-center gap-2">
                        <svg className="w-5 h-5 text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path></svg>
                        {generatedContent.title}
                    </h4>
                    <div className="bg-slate-900 rounded-lg p-4 text-sm font-mono text-slate-300 overflow-x-auto border border-slate-700">
                        <ReactMarkdown>{generatedContent.content}</ReactMarkdown>
                    </div>
                </div>
            )}
        </div>
    </div>
  );
};